name:                jian
version:             0.1.3.0
github:              https://github.com/Meowcolm024/jian
license:             BSD3
author:              Malcolm Law
maintainer:          ""
copyright:           2020 Malcolm Law

extra-source-files:
- README.md
- ChangeLog.md
- examples/*.md
- examples/*.jian

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Meowcolm024/jian/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- parsec >=3.1 && <3.2
- containers >=0.6 && <0.7

library:
  source-dirs: src

executables:
  jian-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jian
    - parsec
    - containers

tests:
  jian-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jian
